### ISSUE TITLE
Failed to run melos commands

### ISSUE THREAD

**Issue by SAGARSURI** [invertase/melos#111]
I am trying to run melos commands( e.g: `melos bs` ) in a project already configured with melos. It was working fine for few days and today suddenly I am getting following error:
```
Unhandled exception:
type 'String' is not a subtype of type 'YamlList' in type cast
#0      MelosWorkspaceConfig.packages (package:melos/src/common/workspace_config.dart:120:48)
#1      MelosWorkspace._loadPackages (package:melos/src/common/workspace.dart:103:33)
#2      MelosWorkspace.loadPackagesWithFilters (package:melos/src/common/workspace.dart:168:49)
#3      MelosCommandRunner.runCommand (package:melos/src/command_runner.dart:213:30)
<asynchronous suspension>
```

**Comment by SAGARSURI** [comment]
Hey @rrousselGit ,
When I configured my project with melos I was using version `0.4.11+1`. Everything was working fine. But when I upgraded to `0.4.11+2`. I am getting the above error when running any command like `melos bs` or `melos clean`. If you need something specific I can share with you.

**Comment by SAGARSURI** [comment]
Hey @rrousselGit 
I was able to resolve it. There was some spelling mistake in my `melos.yaml` file. Thanks
