### ISSUE TITLE
--no-private does not seem to work

### ISSUE THREAD

**Issue by ABausG** [invertase/melos#180]
Based on the documentation of `--no-private` I would expect commands would not be executed in packages that have set `publish_to: none` set in the pubspec file. However for me the commands are executed.

I have the following section in my `melos.yaml`

```
  lint:pub:
    run: >
      melos exec -c 5 --no-private -- \
        "dart pub publish --dry-run"
    select-package:
      ignore: "*example*"
```

The issue occurs when calling it the following ways:

```melos run lint:pub --no-select```

```melos run lint:pub``` (here the package in question appears in the list)

```
# Melos Configuration
  lint:all:
    run: |
      melos run lint:analyze && melos run lint:pub --no-select && melos run lint:format

# Command
melos run lint:all
```

**Comment by ABausG** [comment]
Swapping `--no-private` to `--published` also does not work unfortunately

**Comment by Ehesp** [comment]
Hey, what version of melos are you using?

**Comment by ABausG** [comment]
melos 0.4.11+2

**Comment by Salakar** [comment]
Could you try out `1.0.0-dev.3`? Thanks

**Comment by ABausG** [comment]
Got the following output after running
```
melos run lint:pub --no-private
```

```
Unhandled exception:
Could not find an option named "no-private".

Usage: melos run <name>
-h, --help         Print this usage information.
    --no-select    Skips the prompt to select a package (if defined in the script configuration). Filters defined in
                   the scripts "select-package" options will however still be applied.

Run "melos help" to see global options.
#0      Command.usageException (package:args/command_runner.dart:445:7)
#1      CommandRunner.parse (package:args/command_runner.dart:137:15)
#2      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:119:36)
#3      new Future.sync (dart:async/future.dart:218:31)
#4      CommandRunner.run (package:args/command_runner.dart:119:14)
#5      main (file:///Users/work/.pub-cache/hosted/pub.dartlang.org/melos-1.0.0-dev.3/bin/melos.dart:8:26)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

Interestingly running
```
melos bootstrap -no-private
```
Runs as expected (failing in examples as these are not publishing)

**Comment by ABausG** [comment]
running:
```
melos exec -c 5 --no-private -- \
        "dart pub publish --dry-run"
```

manually (not through melos run) works! So something must happen between melos run and the actual exec command?

**Comment by Salakar** [comment]
Actually, can you try:

```yaml
  lint:pub:
    run: >
      melos exec -c 5 -- \
        "dart pub publish --dry-run"
    select-package:
      ignore: "*example*"
      no-private: true
```

, since specifying `select-package` overrides all filters as far as I know (we should document this if you can confirm it works)
