### ISSUE TITLE
fix:  melos bootstrap error: type 'bool' is not a subtype of type 'String' in type cast

### ISSUE THREAD

**Issue by yhong-emporia** [invertase/melos#270]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

1.5.2

### Description

after setting up a my melos.yaml file with a simple

```yaml
name: monorepo_test

packages:
  - apps/**
  - packages/**
```

and moving my app folder into the apps and my packages into packages I ran `melos bootstrap` and got this error:
```zsh
❯ melos bootstrap
melos bootstrap
   └> /Users/yanminhong/Development/emporia_app_monorepo_test

Running "flutter pub get" in workspace packages...
Unhandled exception:
type 'bool' is not a subtype of type 'String' in type cast
#0      new LinkedHashMap.from.<anonymous closure> (dart:collection/linked_hash_map.dart:187:16)
#1      MapMixin.forEach (dart:collection/maps.dart:123:13)
#2      new LinkedHashMap.from (dart:collection/linked_hash_map.dart:186:11)
#3      _writeYamlString (package:melos/src/yamlicious/yaml_writer.dart:25:22)
#4      _mapToYamlString.<anonymous closure> (package:melos/src/yamlicious/yaml_writer.dart:61:5)
#5      List.forEach (dart:core-patch/growable_array.dart:433:8)
#6      _mapToYamlString (package:melos/src/yamlicious/yaml_writer.dart:55:8)
#7      _writeYamlString (package:melos/src/yamlicious/yaml_writer.dart:25:5)
#8      _mapToYamlString.<anonymous closure> (package:melos/src/yamlicious/yaml_writer.dart:61:5)
#9      List.forEach (dart:core-patch/growable_array.dart:433:8)
#10     _mapToYamlString (package:melos/src/yamlicious/yaml_writer.dart:55:8)
#11     _writeYamlString (package:melos/src/yamlicious/yaml_writer.dart:25:5)
#12     writeYamlString (package:melos/src/yamlicious/yaml_writer.dart:15:3)
#13     toYamlString (package:melos/src/yamlicious/yaml_writer.dart:9:3)
#14     _generateTemporaryProjects (package:melos/src/commands/bootstrap.dart:261:21)
#15     _BootstrapMixin.bootstrap.<anonymous closure> (package:melos/src/commands/bootstrap.dart:29:15)
#16     _BootstrapMixin.bootstrap.<anonymous closure> (package:melos/src/commands/bootstrap.dart:10:7)
#17     _Melos._runLifecycle (package:melos/src/commands/runner.dart:117:15)
#18     _BootstrapMixin.bootstrap (package:melos/src/commands/bootstrap.dart:7:12)
<asynchronous suspension>
#19     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#20     MelosCommandRunner.runCommand (package:melos/src/command_runner.dart:82:5)
<asynchronous suspension>
#21     main (file:///Users/yanminhong/.pub-cache/hosted/pub.dartlang.org/melos-1.5.2/bin/melos.dart:10:5)
<asynchronous suspension>
```

I am able to run `flutter pub get` in the individual apps/packages

### Steps to reproduce

1. run `melos bootstrap` on newly created monorepo with one app and a couple packages

### Expected behavior

bootstrap should finish successfully

**Comment by blaugold** [comment]
This looks like an issue with a `pubspec.yaml` of one of the packages. Could try and bootstrap packages individually until you find the one with the problematic `pubspec.yaml` and post its contents?

You can bootstrap a single package with the following command:
```shell
melos bootstrap --scope <package-name>
```

**Comment by blaugold** [comment]
Closing this issue because the code that caused the exception is no longer used by Melos.
