### ISSUE TITLE
fix:  Android App First Run error

### ISSUE THREAD

**Issue by msxenon** [invertase/melos#309]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

2.3.1 and all versions

### Description

When starting the android studio it keeps indexing and after that it throws and error to the IDE
P.S. its super slow when switching between mono-repos classes

(Error log is attached)

### Steps to reproduce

1. Open your flutter project with android studio
2. wait until it finishes indexing
3. see the error

### Expected behavior

Must be without errors

### Additional context and comments

addEntity: persistent id already exists. Replacing entity with the new one.
Persistent id: ModuleId(name=melos_mobileapp)

Existing entity data: ModuleEntityData(name=melos_mobileapp, type=WEB_MODULE, dependencies=[com.intellij.workspaceModel.storage.bridgeEntities.ModuleDependencyItem$ModuleSourceDependency@6c709a04, LibraryDependency(library=LibraryId(name=Dart SDK, tableId=com.intellij.workspaceModel.storage.bridgeEntities.LibraryTableId$ProjectLibraryTableId@30737538), exported=false, scope=COMPILE), LibraryDependency(library=LibraryId(name=Dart Packages, tableId=com.intellij.workspaceModel.storage.bridgeEntities.LibraryTableId$ProjectLibraryTableId@30737538), exported=false, scope=COMPILE)], classId=0, Companion=com.intellij.workspaceModel.storage.bridgeEntities.ModuleEntityData$Companion@76aa75d2, entitySource=FileInDirectory(directory=file:///Users/moxa/Documents/MyProjects/flutters/CHI/mobile/., fileNameId=15, projectLocation=DirectoryBased(projectDir=file:///Users/moxa/Documents/MyProjects/flutters/CHI/mobile, ideaFolder=file:///Users/moxa/Documents/MyProjects/flutters/CHI/mobile/.idea)), id=0, id=0)
New entity data: ModuleEntityData(name=melos_mobileapp, type=null, dependencies=[com.intellij.workspaceModel.storage.bridgeEntities.ModuleDependencyItem$ModuleSourceDependency@6c709a04], classId=0, Companion=com.intellij.workspaceModel.storage.bridgeEntities.ModuleEntityData$Companion@76aa75d2, entitySource=FileInDirectory(directory=file:///Users/moxa/Documents/MyProjects/flutters/CHI/mobile, fileNameId=9, projectLocation=DirectoryBased(projectDir=file:///Users/moxa/Documents/MyProjects/flutters/CHI/mobile, ideaFolder=file:///Users/moxa/Documents/MyProjects/flutters/CHI/mobile/.idea)), id=1, id=1)

Broken consistency: false

com.intellij.workspaceModel.storage.impl.exceptions.PersistentIdAlreadyExistsException: Entity with persistentId: ModuleId(name=melos_mobileapp) already exist
	at com.intellij.workspaceModel.storage.impl.WorkspaceEntityStorageBuilderImpl.addEntity(WorkspaceEntityStorageImpl.kt:130)
	at com.intellij.workspaceModel.storage.bridgeEntities.BridgeModelModifiableEntitiesKt.addModuleEntity(bridgeModelModifiableEntities.kt:31)
	at com.intellij.workspaceModel.storage.bridgeEntities.BridgeModelModifiableEntitiesKt.addModuleEntity$default(bridgeModelModifiableEntities.kt:29)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.ModuleImlFileEntitiesSerializer.loadModuleEntity(ModuleImlFileEntitiesSerializer.kt:133)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.ModuleImlFileEntitiesSerializer.loadEntities(ModuleImlFileEntitiesSerializer.kt:72)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.JpsProjectSerializersImpl.loadEntitiesAndReportExceptions(JpsProjectSerializersImpl.kt:275)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.JpsProjectSerializersImpl.reloadFromChangedFiles(JpsProjectSerializersImpl.kt:240)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.JpsProjectModelSynchronizer$reloadProjectEntities$2.invoke(JpsProjectModelSynchronizer.kt:83)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.JpsProjectModelSynchronizer$reloadProjectEntities$2.invoke(JpsProjectModelSynchronizer.kt:46)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.JpsProjectModelSynchronizer.loadAndReportErrors(JpsProjectModelSynchronizer.kt:103)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.JpsProjectModelSynchronizer.reloadProjectEntities(JpsProjectModelSynchronizer.kt:83)
	at com.intellij.configurationStore.StoreReloadManagerImpl.reloadAdditionalConfigurations(StoreReloadManagerImpl.kt:99)
	at com.intellij.configurationStore.StoreReloadManagerImpl.access$reloadAdditionalConfigurations(StoreReloadManagerImpl.kt:47)
	at com.intellij.configurationStore.StoreReloadManagerImpl$changedFilesAlarm$1.run(StoreReloadManagerImpl.kt:89)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:240)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:391)
	at com.intellij.util.Alarm$Request.run(Alarm.java:377)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:220)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:486)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by blaugold** [comment]
Can you check if there are more than one `pubspec.yaml` files in your repo that have `melos_mobileapp` as the `name`?
This should not be the case. Every package within your repo should have a unique name.
