### ISSUE TITLE
Command `melos bootstrap` breaking on github actions on 0.3.12

### ISSUE THREAD

**Issue by rafaelcmm** [invertase/melos#39]
Command `melos bootstrap` is breaking on github actions since this new version.

Please check the following logs:

```
melos bootstrap
   └> /Users/rafaelcmm/Workspace/qwkin-dart

Bootstrapping project...               SUCCESS
Linking project packages...            SUCCESS
Running postbootstrap script...

melos run postbootstrap
   └> tuneup --version || pub global activate tuneup
       └> RUNNING

tuneup version 0.3.7

melos run postbootstrap
   └> tuneup --version || pub global activate tuneup
       └> SUCCESS

Packages:
Unhandled exception:
NoSuchMethodError: The method 'forEach' was called on null.
Receiver: null
Tried calling: forEach(Closure: (MelosPackage) => Null)
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      BootstrapCommand.run (package:melos/src/command/bootstrap.dart:89:31)
<asynchronous suspension>
#2      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#3      MelosCommandRunner.runCommand (package:melos/src/command_runner.dart:170:17)
<asynchronous suspension>
#4      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#5      new Future.sync (dart:async/future.dart:224:31)
#6      CommandRunner.run (package:args/command_runner.dart:112:14)
#7      main (file:///Users/rafaelcmm/.pub-cache/hosted/pub.dartlang.org/melos-0.3.12/bin/melos.dart:4:31)
#8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

All packages are being installed correctly and assigned to path.

**Comment by Salakar** [comment]
Fix going through CI currently - will post a release shortly, sorry about that 😓

**Comment by Salakar** [comment]
`0.3.12+1` is now available. Thanks
