### ISSUE TITLE
fix:  Failed to authenticate with GitHub when running melos version command

### ISSUE THREAD

**Issue by KoheiKanagu** [invertase/melos#528]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

3.0.1

### Description

When running `melos version` on a private repository, the following error occurred.

```sh
Username for 'https://github.com': KoheiKanagu
Password for 'https://KoheiKanagu@github.com':
Unhandled exception:
ProcessException: Melos: Failed executing a git command:  remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/KoheiKanagu/foo/'

  Command: git fetch --tags
#0      gitExecuteCommand (package:melos/src/common/git.dart:85:5)
<asynchronous suspension>
#1      gitFetchTags (package:melos/src/common/git.dart:231:3)
<asynchronous suspension>
#2      _VersionMixin._version (package:melos/src/commands/version.dart:118:7)
<asynchronous suspension>
#3      _Melos._runLifecycle (package:melos/src/commands/runner.dart:124:7)
<asynchronous suspension>
#4      VersionCommand.run (package:melos/src/command_runner/version.dart:236:7)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      MelosCommandRunner.runCommand (package:melos/src/command_runner.dart:90:5)
<asynchronous suspension>
#7      melosEntryPoint (package:melos/src/command_runner.dart:143:5)
<asynchronous suspension>
```

### Steps to reproduce

1. Run `melos version` on a private repository.

### Expected behavior

Even in a private repository, `git fetch --tags` should succeed.

### Additional context and comments

Setting fetchTags to false as follows will prevent this error from occurring.
```yaml
command:
  version:
    fetchTags: false
```

**Comment by KoheiKanagu** [comment]
I'm sorry, it was my mistake. 
The reason was that `git remote -v` showed that it was using https.
