### ISSUE TITLE
fix:  BootstrapException: Failed to install. with some package

### ISSUE THREAD

**Issue by ChangJoo-Park** [invertase/melos#553]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

3.1.1

### Description

melos bootstrap failed with [flutter_naver_map](https://pub.dev/packages/flutter_naver_map) 

```
Resolving dependencies...
  collection 1.17.1 (1.18.0 available)
  matcher 0.12.15 (0.12.16 available)
  material_color_utilities 0.2.0 (0.8.0 available)
  source_span 1.9.1 (1.10.0 available)
  stack_trace 1.11.0 (1.11.1 available)
  stream_channel 2.1.1 (2.1.2 available)
  test_api 0.5.1 (0.6.1 available)
Got dependencies!
This app is using a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to migrate this app to the V2 embedding.
Take a look at the docs for migrating an app: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
The plugin `flutter_naver_map` requires your app to be migrated to the Android embedding v2. Follow the steps on the migration doc above and re-run this command.
BootstrapException: Failed to install.: my_package at <package path>
```

I need to get error from `BootstrapException`.

### Steps to reproduce

1. initialize melos project
2. add flutter_naver_map into package
3. bootstrap with `melos bs`

### Expected behavior

Install all packages successfully

### Additional context and comments

```
[   +1 ms] The plugin `flutter_naver_map` requires your app to be migrated to the Android embedding v2. Follow the steps on the migration doc above and re-run this command.
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _writeAndroidPluginRegistrant (package:flutter_tools/src/flutter_plugins.dart:438:11)
           #2      injectPlugins (package:flutter_tools/src/flutter_plugins.dart:1150:11)
           <asynchronous suspension>
           #3      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:374:5)
           <asynchronous suspension>
           #4      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:326:7)
           <asynchronous suspension>
           #5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
           <asynchronous suspension>
           #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #13     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
```

**Comment by ChangJoo-Park** [comment]
I think it may problem of flutter sdk :(

**Comment by vityaz-it** [comment]
> I think it may problem of flutter sdk :(

Upgrade flutter sdk and melos global package to 3.1.1 version
```
dart pub global activate melos 
melos -v
```

**Comment by skiryuk** [comment]
> I think it may problem of flutter sdk :(

Upgrade flutter sdk and melos global package to 3.1.1 version

```
dart pub global activate melos 
melos -v
```
