### ISSUE TITLE
Run `melos bootstrap` fails when using `PUB_HOSTED_URL`

### ISSUE THREAD

**Issue by lam-nv** [invertase/melos#82]
Hi Team,

I encountered the issue when run `melos bootstrap`, see details below. 

Result of `flutter doctor`:
```log
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 1.22.6, on macOS 11.0.1 20B50 darwin-x64, locale en)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.54.3)
[✓] Connected device (3 available)

• No issues found!
```

Logs:
```log
$ melos bootstrap
melos bootstrap
   └> /Users/USER_ID/...project_folder/my_project

Running "flutter pub get" in workspace packages...
  ✓ x4
     └> ./packages/x4
  ✓ x4
     └> ./packages/x4
  ✓ x3
     └> ./packages/x3
  ✓ x2
     └> ./packages/x2
  ✓ x1
     └> ./packages/x1

Linking workspace packages...
  > SUCCESS

Generating IntelliJ IDE files...
Unhandled exception:
FileSystemException: Cannot open file, path = '/Users/USER_ID/.pub-cache/hosted/pub.dartlang.org/melos-0.4.7/templates/intellij/modules/flutter_plugin_module.iml.tmpl' (OS Error: No such file or directory, errno = 2)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
#1      _RootZone.runUnary (dart:async/zone.dart:1450:54)
#2      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#3      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#4      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#5      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#6      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#9      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

Is this issue related to customizing the variable PUB_HOSTED_URL?

Thanks for investigated.

**Comment by Salakar** [comment]
> Is this issue related to customizing the variable PUB_HOSTED_URL?

I guess it is 😅  is `PUB_HOSTED_URL` just an environment variable that replaces `pub.dartlang.org`? Not familiar with it.

If it is then I guess `/Users/USER_ID/.pub-cache/hosted/pub.dartlang.org/melos-0.4.7` the `pub.dartlang.org` part here is incorrect and should be `$PUB_HOSTED_URL` - can you confirm that location exists on your local file system for the hosted url you've set on `PUB_HOSTED_URL` - if it's there then I should be able to fix fairly straightforward

**Comment by Salakar** [comment]
@lam-nv could you try out Melos version `0.4.10-dev.1` - this should be fixed now thanks to @shyndman

**Comment by lam-nv** [comment]
> @lam-nv could you try out Melos version `0.4.10-dev.1` - this should be fixed now thanks to @shyndman
> 
> ```
> dart pub global activate melos 0.4.10-dev.1
> ```

Now, it works. 

Many thanks, @Salakar and @shyndman
