### ISSUE TITLE
Error when executing melos command

### ISSUE THREAD

**Issue by pedroculque** [invertase/melos#89]
Guys I have a problem, I've been running melos in a normal way in my project with modules, recently started to generate the following error, every time I run any command from melo

```
Unhandled exception:
NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      StringScanner.isDone (package:string_scanner/src/string_scanner.dart:53:41)
#2      Parser._parseSequence (package:glob/src/parser.dart:38:18)
#3      Parser.parse (package:glob/src/parser.dart:30:27)
#4      new Glob (package:glob/glob.dart:108:44)
#5      MelosWorkspace.loadPackagesWithFilters.<anonymous closure>.<anonymous closure> (package:melos/src/common/workspace.dart:142:16)
#6      ListMixin.firstWhere (dart:collection/list.dart:161:15)
#7      MelosWorkspace.loadPackagesWithFilters.<anonymous closure> (package:melos/src/common/workspace.dart:141:46)
#8      _WhereStream._handleData (dart:async/stream_pipe.dart:193:24)
#9      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:157:13)
#10     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#13     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:127:11)
#14     _WhereStream._handleData (dart:async/stream_pipe.dart:199:12)
#15     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:157:13)
#16     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#20     _StreamController._add (dart:async/stream_controller.dart:682:7)
#21     _StreamController.add (dart:async/stream_controller.dart:624:5)
#22     _AsyncDirectoryLister.next.<anonymous closure> (dart:io/directory_impl.dart:383:26)
#23     _RootZone.runUnary (dart:async/zone.dart:1450:54)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#26     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#27     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#28     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#29     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#30     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#31     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#32     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

**Package melos is currently active at version 0.4.1.**

**Comment by shyndman** [comment]
It looks like this is happening because one of the `packages` globs in `melos.yaml` is null.

Any recent changes to your `melos.yaml`?

**Comment by pedroculque** [comment]
Hey, thank you so much for the information, really my melos.yaml was declaring a package null, like this:
packages:
   **-** package_1/ **
   **-** package_2 / **
   **-**
AI was empty space and made the melos generate this error, remove the **-** to solve problem ;) thanks
